#!/usr/bin/env python3
"""Generates dev/fixture/.trmnlp.yml: an offline preview built from the samples in dev/samples
(real snapshots trimmed by dev/fetch_samples.py, plus a synthetic Artificial Analysis file).

The samples are injected through `variables.sources`, a map from URL (or "<zip url>#<member>")
to the text the Serverless function would have downloaded; `offline: true` makes the function
fail loudly instead of reaching the network. The clock is frozen for stable renders.

Usage: python3 dev/make_fixture.py   (then bin/dev fixture)
"""
import json
import sys
from datetime import datetime, timezone
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "src"))
import transform as tf  # noqa: E402

SAMPLES = ROOT / "dev" / "samples"
NOW = datetime(2026, 9, 11, 12, 0, 0, tzinfo=timezone.utc)  # 14:00 in Paris (CEST)

DEFAULT_FIELDS = {
    "board_1": "arena_text",
    "board_2": "epoch_eci",
    "board_3": "none",
    "max_models": "10",
    "open_weights_only": "no",
    "highlight": "",
    "title": "",
    "aa_api_key": "",
    "livebench_version": "",
    "language": "auto",
}

FROZEN_CLOCK = {"trmnl": {"system": {"timestamp_utc": int(NOW.timestamp())}}}


def build_sources():
    """URL -> text, for every sample file."""
    sources = {}
    arena = SAMPLES / "arena"
    pointer = (arena / "latest.json").read_text(encoding="utf-8")
    sources[tf.ARENA_POINTER] = pointer
    path = json.loads(pointer)["path"]
    for f in sorted(arena.glob("*.json")):
        if f.name != "latest.json":
            sources[tf.ARENA_DATA + path + "/" + f.name] = f.read_text(encoding="utf-8")
    epoch = SAMPLES / "epoch"
    sources[tf.EPOCH_ECI] = (epoch / "eci_scores.csv").read_text(encoding="utf-8")
    for f in sorted(epoch.glob("*.csv")):
        if f.name != "eci_scores.csv":
            sources[tf.EPOCH_ZIP + "#" + f.name] = f.read_text(encoding="utf-8")
    for f in sorted((SAMPLES / "livebench").iterdir()):
        sources[tf.LIVEBENCH + f.name] = f.read_text(encoding="utf-8")
    sources[tf.AA_MODELS] = (SAMPLES / "artificialanalysis" / "models_free.synthetic.json").read_text(encoding="utf-8")
    return sources


def build_variables(sources=None, offline=True):
    return {**FROZEN_CLOCK, "offline": offline, "sources": sources if sources is not None else build_sources()}


def render_config(custom_fields, variables, watch=("../../src", ".trmnlp.yml"), comment=""):
    """A .trmnlp.yml file: YAML accepts JSON, so the variables block is written as-is."""
    lines = [comment.rstrip("\n"), "---", "watch:"] if comment else ["---", "watch:"]
    lines += [f"  - {w}" for w in watch]
    lines += ["time_zone: Europe/Paris", "custom_fields:"]
    lines += [f"  {k}: {json.dumps(str(v), ensure_ascii=False)}" for k, v in custom_fields.items()]
    lines += ["# YAML accepts JSON: the block below is merged on top of the plugin data.",
              "variables: " + json.dumps(variables, ensure_ascii=False)]
    return "\n".join(lines) + "\n"


def main():
    sources = build_sources()
    comment = ("# Offline preview: sample leaderboards from dev/samples, frozen clock.\n"
               "# Generated by dev/make_fixture.py, do not edit by hand. Run: bin/dev fixture")
    out = ROOT / "dev" / "fixture" / ".trmnlp.yml"
    out.parent.mkdir(parents=True, exist_ok=True)
    link = out.parent / "src"
    if not link.exists():
        link.symlink_to(ROOT / "src")
    out.write_text(render_config(DEFAULT_FIELDS, build_variables(sources), comment=comment), encoding="utf-8")
    print(f"wrote {out} ({len(sources)} sources, {out.stat().st_size // 1024} KB)")


if __name__ == "__main__":
    main()
